package com.zcpu.tzzmod.webadmin;

final class WebAdminLogicChainVbdScripts {
    private WebAdminLogicChainVbdScripts() {
    }

    static String appJs() {
        return new StringBuilder().append("""
                const logicChainV16VbdTriggerGraphSummaryMarkers='data-logic-chain-vbd-trigger-readable-draft-summary data-logic-chain-vbd-native-json-not-primary-summary data-logic-chain-vbd-trigger-channel-draft-edge data-logic-chain-vbd-trigger-graph-render-before-save data-logic-chain-vbd-capture-modal-captured-state data-logic-chain-vbd-capture-modal-applied-state data-logic-chain-vbd-capture-button-state data-logic-chain-vbd-itemsubmit-capture-button-state data-logic-chain-vbd-container-capture-button-state';
                function logicChainJsonObject(text){try{const value=JSON.parse(String(text||'{}'));return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}catch(_){return {};}}
                function logicChainJsonArray(text){try{const value=JSON.parse(String(text||'[]'));return Array.isArray(value)?value:[];}catch(_){return [];}}
                function logicChainVbdNativeOriginalValues(draft){return logicChainJsonObject(draft?.originalJson||'{}');}
                function logicChainVbdNormalizeConditionRows(rows){return (rows||[]).filter(r=>!isBlank(r?.property)||!isBlank(r?.value)).map(r=>({property:String(r.property||''),value:String(r.value||'')}));}
                function logicChainVbdConditionRowsText(rows){const list=logicChainVbdNormalizeConditionRows(rows);return list.length?list.map(r=>`${r.property}=${r.value}`).join('，'):'未配置';}
                function logicChainVbdReadableValue(value,kind='text'){if(kind==='bool')return value?'是':'否';if(kind==='rows')return logicChainVbdConditionRowsText(value);if(kind==='ticks')return `${Number(value||0)} tick`;if(kind==='channel')return normalizeLogicChainDraftChannel(value)||'未设置';if(kind==='gate')return value||'未配置';if(value===undefined||value===null||value==='')return '未配置';return String(value);}
                function logicChainVbdSameSummaryValue(a,b,kind='text'){const normalize=value=>kind==='rows'?JSON.stringify(logicChainVbdNormalizeConditionRows(value)):(kind==='channel'?normalizeLogicChainDraftChannel(value):String(value??''));return normalize(a)===normalize(b);}
                function logicChainVbdNativeTriggerSpecs(){return [
                  {type:'redstone_powered',label:'红石 / 受电状态',enabledKey:'redstoneEnabled',fields:[['启用','redstoneEnabled','bool'],['模式','redstoneMode','text'],['输出频道','channel','channel'],['断电频道','offChannel','channel'],['条件组','redstoneConditionGroupId','gate']]},
                  {type:'blockstate',label:'BlockState 条件',enabledKey:'blockStateEnabled',fields:[['启用','blockStateEnabled','bool'],['模式','conditionMode','text'],['输出频道','channel','channel'],['退出频道','offChannel','channel'],['属性条件','conditionRows','rows'],['条件组','blockStateConditionGroupId','gate']]},
                  {type:'right_click',label:'右键交互',enabledKey:'interactionEnabled',fields:[['启用','interactionEnabled','bool'],['交互频道','interactChannel','channel'],['冷却','interactionCooldownTicks','ticks'],['交互条件组','interactionConditionGroupId','gate']]},
                  {type:'itemSubmit',label:'itemSubmit',enabledKey:'interactionEnabled',fields:[['itemSubmit 条件组','itemSubmitConditionGroupId','gate']]},
                  {type:'container_open',label:'容器打开',enabledKey:'containerOpenEnabled',fields:[['启用','containerOpenEnabled','bool'],['输出频道','containerOpenChannel','channel'],['条件组','containerOpenConditionGroupId','gate'],['容器冷却','containerCooldownTicks','ticks']]},
                  {type:'container_close',label:'容器关闭',enabledKey:'containerCloseEnabled',fields:[['启用','containerCloseEnabled','bool'],['输出频道','containerCloseChannel','channel'],['条件组','containerCloseConditionGroupId','gate'],['容器冷却','containerCooldownTicks','ticks']]},
                  {type:'container_change',label:'容器内容变化',enabledKey:'containerChangeEnabled',fields:[['启用','containerChangeEnabled','bool'],['输出频道','containerChangeChannel','channel'],['检查间隔','containerChangeCheckIntervalTicks','ticks'],['条件组','containerChangeConditionGroupId','gate'],['容器冷却','containerCooldownTicks','ticks']]}
                ];}
                function logicChainVbdStoredNativeTriggerDraft(d){return d?.virtualBlockDevice?.nativeTriggerDraft||null;}
                function logicChainVbdNativeTriggerReadableDraftRows(d){const draft=logicChainVbdStoredNativeTriggerDraft(d);if(!draft||!vbdNativeTriggerDirty(draft))return [];const before=logicChainVbdNativeOriginalValues(draft),after=draft.values||{},rows=[];logicChainVbdNativeTriggerSpecs().forEach(spec=>{const changed=[];spec.fields.forEach(([label,key,kind])=>{if(!logicChainVbdSameSummaryValue(before[key],after[key],kind))changed.push({label,key,kind});});if(!changed.length)return;changed.forEach(field=>rows.push({title:`VBD 触发项更新：${spec.label}`,field:field.label,before:logicChainVbdReadableValue(before[field.key],field.kind),after:logicChainVbdReadableValue(after[field.key],field.kind),kind:'field',vbdNativeTriggerReadable:true}));});if(!rows.length)rows.push({title:d?.displayName||d?.label||d?.deviceId||'VBD',field:'VBD 触发项配置',before:'原配置',after:'已更新（部分字段无法摘要）',kind:'field',vbdNativeTriggerReadable:true});return rows;}
                function logicChainVbdRequirementListText(rows,kind){const list=Array.isArray(rows)?rows:[];if(!list.length)return '0 条';const head=list.slice(0,3).map((r,index)=>`${r.displayName||r.templateSummary||r.itemId||`${kind} #${index+1}`} x${r.count??r.requiredCount??1}`).join('；');return `${list.length} 条 · ${head}${list.length>3?'；...':''}`;}
                function logicChainVbdRequirementDraftReadableRows(d){if(String(d?.kind||'').toLowerCase()!=='virtual_block_device')return [];const vbd=d.virtualBlockDevice||{},rows=[],beforeItems=logicChainJsonArray(d.original?.vbdItemSubmitDraftJson),beforeContainers=logicChainJsonArray(d.original?.vbdContainerDraftJson),afterItems=vbd.itemSubmitRequirements||[],afterContainers=vbd.containerRequirements||[];if(JSON.stringify(beforeItems)!==JSON.stringify(afterItems))rows.push({title:'VBD 触发项更新：itemSubmit',field:'捕获 requirement',before:logicChainVbdRequirementListText(beforeItems,'itemSubmit'),after:logicChainVbdRequirementListText(afterItems,'itemSubmit'),kind:'field',vbdTriggerRequirementReadable:true});if(JSON.stringify(beforeContainers)!==JSON.stringify(afterContainers))rows.push({title:'VBD 触发项更新：容器内容变化',field:'container 捕获模板',before:logicChainVbdRequirementListText(beforeContainers,'container'),after:logicChainVbdRequirementListText(afterContainers,'container'),kind:'field',vbdTriggerRequirementReadable:true});return rows;}
                const logicChainExistingDiffRowsBeforeV16=logicChainExistingDiffRows;logicChainExistingDiffRows=function(d){const rows=logicChainExistingDiffRowsBeforeV16(d);if(String(d?.kind||'').toLowerCase()!=='virtual_block_device')return rows;const hidden=new Set(['nativeTriggerJson','vbdItemSubmitDraftJson','vbdContainerDraftJson']);return rows.filter(row=>!hidden.has(row.field)).concat(logicChainVbdNativeTriggerReadableDraftRows(d),logicChainVbdRequirementDraftReadableRows(d));};
                """)
.append("""
                function logicChainVbdNativeTriggerOutputRows(values={}){const rows=[];const push=(type,label,channel,enabled)=>{const normalized=normalizeLogicChainDraftChannel(channel);if(enabled&&normalized)rows.push({type,label,channel:normalized});};push('redstone_powered','红石 / 受电状态',values.channel,values.redstoneEnabled);push('redstone_powered_off','红石断电',values.offChannel,values.redstoneEnabled);push('blockstate','BlockState 条件',values.channel,values.blockStateEnabled);push('blockstate_exit','BlockState 退出',values.offChannel,values.blockStateEnabled);push('right_click','右键交互',values.interactChannel,values.interactionEnabled);push('container_open','容器打开',values.containerOpenChannel,values.containerOpenEnabled);push('container_close','容器关闭',values.containerCloseChannel,values.containerCloseEnabled);push('container_change','容器内容变化',values.containerChangeChannel,values.containerChangeEnabled);return rows;}
                function logicChainVbdNativeTriggerOutputChannels(values){return Array.from(new Set(logicChainVbdNativeTriggerOutputRows(values).map(row=>row.channel).filter(Boolean)));}
                function logicChainVbdTriggerOutputSummary(values){const rows=logicChainVbdNativeTriggerOutputRows(values);return rows.length?rows.slice(0,3).map(row=>`${row.label} -> ${row.channel}`).join('；')+(rows.length>3?'；...':''):'触发项草稿尚未设置输出频道';}
                const logicChainOverlayHasConnectionChangesBeforeV16=logicChainOverlayHasConnectionChanges;logicChainOverlayHasConnectionChanges=function(editor){if(logicChainOverlayHasConnectionChangesBeforeV16(editor))return true;return logicChainExistingNodeDraftsForPreview(editor).some(d=>{if(String(d?.kind||'').toLowerCase()!=='virtual_block_device')return false;const draft=logicChainVbdStoredNativeTriggerDraft(d);if(!draft||!vbdNativeTriggerDirty(draft))return false;const before=logicChainVbdNativeTriggerOutputChannels(logicChainVbdNativeOriginalValues(draft)),after=logicChainVbdNativeTriggerOutputChannels(draft.values||{});return before.length!==after.length||before.some(channel=>!after.includes(channel))||after.some(channel=>!before.includes(channel));});};
                """)
.append("""
                function logicChainApplyVbdNativeTriggerDraftGraphOverlay(graph){const editor=appState.logicChainEditor||{};if(!editor.active||!graph?.nodes)return graph;const nodes=(graph.nodes||[]).map(n=>({...n,metadata:{...(n.metadata||{})}})),nodeMap={};nodes.forEach(n=>{if(n.id)nodeMap[n.id]=n;});let edges=(graph.edges||[]).map(e=>({...e,metadata:{...(e.metadata||{})}}));logicChainExistingNodeDraftsForPreview(editor).forEach(d=>{if(String(d?.kind||'').toLowerCase()!=='virtual_block_device')return;const draft=logicChainVbdStoredNativeTriggerDraft(d);if(!draft||!vbdNativeTriggerDirty(draft))return;const target=logicChainFindDraftTargetNode(nodes,d),id=target?.id;if(!target||!id)return;const beforeChannels=logicChainVbdNativeTriggerOutputChannels(logicChainVbdNativeOriginalValues(draft)),afterRows=logicChainVbdNativeTriggerOutputRows(draft.values||{}),afterChannels=new Set(afterRows.map(row=>row.channel));target.subtitle=`触发项草稿 · ${logicChainVbdTriggerOutputSummary(draft.values||{})}`;target.metadata={...(target.metadata||{}),dataLogicChainVbdTriggerGraphRenderBeforeSave:true,vbdTriggerDraftGraphRenderBeforeSave:true,vbdTriggerDraftSummary:logicChainVbdTriggerOutputSummary(draft.values||{})};beforeChannels.filter(channel=>!afterChannels.has(channel)).forEach(channel=>{edges=edges.filter(edge=>!(edge.from===id&&edge.type==='vbd_outputs_channel'&&logicChainOverlayEdgeMatchesChannel(edge,nodeMap,'to',channel)));});afterRows.forEach(row=>{logicChainEnsureDraftChannelNode(nodes,nodeMap,row.channel,logicChainDraftChannelInfo(editor,row.channel));const channelId=logicChainDraftChannelNodeId(row.channel),exists=edges.some(edge=>edge.from===id&&edge.type==='vbd_outputs_channel'&&logicChainOverlayEdgeMatchesChannel(edge,nodeMap,'to',row.channel));if(!exists)edges.push({from:id,to:channelId,type:'vbd_outputs_channel',label:`触发项草稿：${row.label}`,style:'dashed',pathGroupId:'draft',visualStyle:'draft-highlight',referenceEdge:false,metadata:{draft:true,draftPreview:true,logicChainDraftOverlay:true,dataLogicChainVbdTriggerChannelDraftEdge:true,dataLogicChainVbdTriggerGraphRenderBeforeSave:true,triggerType:row.type,saveUsesCanonicalChannel:true}});});});return {...graph,nodes,edges,metadata:{...(graph.metadata||{}),dataLogicChainVbdTriggerGraphRenderBeforeSave:true,vbdTriggerDraftGraphRenderBeforeSave:true}};}
                const logicChainRenderedGraphWithDraftOverlayBeforeV16=logicChainRenderedGraphWithDraftOverlay;logicChainRenderedGraphWithDraftOverlay=function(graph){return logicChainApplyVbdNativeTriggerDraftGraphOverlay(logicChainRenderedGraphWithDraftOverlayBeforeV16(graph));};
                const logicChainNodeMarkersBeforeV16=logicChainNodeMarkers;logicChainNodeMarkers=function(node){const base=logicChainNodeMarkersBeforeV16(node),m=node?.metadata||{},extras=[];if(m.dataLogicChainVbdTriggerGraphRenderBeforeSave||m.vbdTriggerDraftGraphRenderBeforeSave)extras.push('data-logic-chain-vbd-trigger-graph-render-before-save="true"');return `${base}${extras.length?' '+extras.join(' '):''}`;};
                function logicChainScheduleVbdNativeTriggerDraftGraphRefresh(){const e=appState.logicChainEditor;if(!e?.active||!appState.currentLogicChainGraph)return;if(appState.logicChainVbdNativeTriggerGraphRefreshPending)return;appState.logicChainVbdNativeTriggerGraphRefreshPending=true;(typeof requestAnimationFrame==='function'?requestAnimationFrame:setTimeout)(()=>{appState.logicChainVbdNativeTriggerGraphRefreshPending=false;if(appState.logicChainEditor?.active&&appState.currentLogicChainGraph)renderLogicChainViewer(appState.currentLogicChainGraph,appState.logicChainCanvas.routeInfo||{fallback:'#/logic-chains'}, {silent:true});});}
                """)
.append("""
                function logicChainCaptureTerminal(draft){return !!(draft?.logicChainDraftContext&&['saved','completed'].includes(String(draft.status||''))&&!draft.active);}
                function logicChainCaptureFooter(draft,kind){const item=kind==='item',closeAttrs=item?singleItemSubmitActionAttrs('single-item-submit-close',draft.deviceId,!!draft.saving):containerTemplateActionAttrs('container-template-close',draft.deviceId,!!draft.saving),startAttrs=item?singleItemSubmitActionAttrs('single-item-submit-start',draft.deviceId,!!draft.saving,'重新捕获会打开新的游戏内 GUI。'):containerTemplateActionAttrs('container-template-start',draft.deviceId,!!draft.saving,'重新捕获会打开新的游戏内 GUI。'),stateAttr=item?'data-logic-chain-vbd-itemsubmit-capture-button-state="true"':'data-logic-chain-vbd-container-capture-button-state="true"',applied=draft.logicChainDraftApplied?'true':'false';return `<button class="wa-btn primary" ${closeAttrs} data-logic-chain-vbd-capture-button-state="true" ${stateAttr} data-logic-chain-vbd-capture-modal-captured-state="true" data-logic-chain-vbd-capture-modal-applied-state="${applied}">${icon('check-pass')}<span>${draft.logicChainDraftApplied?'已加入草稿，返回触发项':'返回触发项'}</span></button><button class="wa-btn ghost" ${startAttrs} data-logic-chain-vbd-capture-button-state="secondary-recapture">${icon('selection')}<span>重新捕获</span></button>`;}
                const singleItemSubmitStatusLineBeforeV16=singleItemSubmitStatusLine;singleItemSubmitStatusLine=function(draft){const html=singleItemSubmitStatusLineBeforeV16(draft);if(!logicChainCaptureTerminal(draft))return html;const applied=draft.logicChainDraftApplied?'已加入当前 Logic Chain 草稿':'已捕获，可返回触发项草稿';return html.replace('</div>',`<span data-logic-chain-vbd-capture-modal-captured-state="true" data-logic-chain-vbd-capture-modal-applied-state="${draft.logicChainDraftApplied?'true':'false'}">${applied}</span></div>`);};
                const containerTemplateStatusLineBeforeV16=containerTemplateStatusLine;containerTemplateStatusLine=function(draft){const html=containerTemplateStatusLineBeforeV16(draft);if(!logicChainCaptureTerminal(draft))return html;const applied=draft.logicChainDraftApplied?'已加入当前 Logic Chain 草稿':'已捕获，可返回触发项草稿';return html.replace('</div>',`<span data-logic-chain-vbd-capture-modal-captured-state="true" data-logic-chain-vbd-capture-modal-applied-state="${draft.logicChainDraftApplied?'true':'false'}">${applied}</span></div>`);};
                const showSingleItemSubmitSessionModalBeforeV16=showSingleItemSubmitSessionModal;showSingleItemSubmitSessionModal=function(deviceId){const draft=appState.singleItemSubmitSession;if(!logicChainCaptureTerminal(draft)||!sameDeviceRef(draft.deviceId,deviceId))return showSingleItemSubmitSessionModalBeforeV16(deviceId);openWebAdminModal('Logic Chain itemSubmit 捕获',singleItemSubmitSessionBody(draft),logicChainCaptureFooter(draft,'item'),{className:'wa-config-modal wa-single-item-submit-modal',onClose:async()=>closeSingleItemSubmitSessionModal(draft.deviceId)});};
                const showContainerTemplateSessionModalBeforeV16=showContainerTemplateSessionModal;showContainerTemplateSessionModal=function(deviceId){const draft=appState.containerTemplateSession;if(!logicChainCaptureTerminal(draft)||!sameDeviceRef(draft.deviceId,deviceId))return showContainerTemplateSessionModalBeforeV16(deviceId);openWebAdminModal('Logic Chain container 捕获',containerTemplateSessionBody(draft),logicChainCaptureFooter(draft,'container'),{className:'wa-config-modal wa-container-template-modal',onClose:async()=>closeContainerTemplateSessionModal(draft.deviceId)});};
                """)
.append("""
                const logicChainV17VbdCaptureWritebackMarkers='data-logic-chain-vbd-trigger-stable-identity data-logic-chain-vbd-trigger-no-duplicate-card data-logic-chain-vbd-trigger-target-channel-only data-logic-chain-vbd-trigger-source-card-draft data-logic-chain-vbd-capture-cancelled-restart-button data-logic-chain-vbd-capture-failed-restart-button data-logic-chain-vbd-capture-retry-click-capture data-logic-chain-vbd-capture-retry-pointerup data-logic-chain-vbd-capture-retry-not-disabled-by-precheck data-logic-chain-vbd-itemsubmit-draft-writeback data-logic-chain-vbd-container-draft-writeback data-logic-chain-vbd-capture-realtime-draft-writeback data-logic-chain-vbd-capture-fail-closed-writeback';
                function logicChainVbdTriggerIdentity(row){return String(row?.triggerKey||row?.type||'trigger').trim().toLowerCase()||'trigger';}
                function logicChainVbdDedupTriggerOutputRows(rows){const out=[];const seen=new Set();(rows||[]).forEach(row=>{const channel=normalizeLogicChainDraftChannel(row?.channel);if(!channel)return;const triggerKey=logicChainVbdTriggerIdentity(row),key=`${triggerKey}->${channel}`;if(seen.has(key))return;seen.add(key);out.push({...row,channel,triggerKey,stableTriggerIdentity:triggerKey});});return out;}
                const logicChainVbdNativeTriggerOutputRowsBeforeV17=logicChainVbdNativeTriggerOutputRows;logicChainVbdNativeTriggerOutputRows=function(values={}){return logicChainVbdDedupTriggerOutputRows(logicChainVbdNativeTriggerOutputRowsBeforeV17(values));};
                function logicChainVbdDraftEdgeTargetChannel(edge,nodeMap){return logicChainOverlayChannelForNode(nodeMap,edge?.to);}
                logicChainApplyVbdNativeTriggerDraftGraphOverlay=function(graph){const editor=appState.logicChainEditor||{};if(!editor.active||!graph?.nodes)return graph;const nodes=(graph.nodes||[]).map(n=>({...n,metadata:{...(n.metadata||{})}})),nodeMap={};nodes.forEach(n=>{if(n.id)nodeMap[n.id]=n;});let edges=(graph.edges||[]).map(e=>({...e,metadata:{...(e.metadata||{})}}));logicChainExistingNodeDraftsForPreview(editor).forEach(d=>{if(String(d?.kind||'').toLowerCase()!=='virtual_block_device')return;const draft=logicChainVbdStoredNativeTriggerDraft(d);if(!draft||!vbdNativeTriggerDirty(draft))return;const target=logicChainFindDraftTargetNode(nodes,d),id=target?.id;if(!target||!id)return;const afterRows=logicChainVbdNativeTriggerOutputRows(draft.values||{}),afterChannels=new Set(afterRows.map(row=>row.channel));target.subtitle=`触发项草稿 · ${logicChainVbdTriggerOutputSummary(draft.values||{})}`;target.metadata={...(target.metadata||{}),dataLogicChainVbdTriggerGraphRenderBeforeSave:true,vbdTriggerDraftGraphRenderBeforeSave:true,vbdTriggerDraftSummary:logicChainVbdTriggerOutputSummary(draft.values||{}),dataLogicChainVbdTriggerStableIdentity:true,dataLogicChainVbdTriggerNoDuplicateCard:true,dataLogicChainVbdTriggerTargetChannelOnly:true};edges=edges.filter(edge=>{if(edge.from!==id||edge.type!=='vbd_outputs_channel')return true;const channel=logicChainVbdDraftEdgeTargetChannel(edge,nodeMap);return channel&&afterChannels.has(channel);});afterRows.forEach(row=>{logicChainEnsureDraftChannelNode(nodes,nodeMap,row.channel,logicChainDraftChannelInfo(editor,row.channel));const channelId=logicChainDraftChannelNodeId(row.channel),exists=edges.some(edge=>edge.from===id&&edge.type==='vbd_outputs_channel'&&logicChainOverlayEdgeMatchesChannel(edge,nodeMap,'to',row.channel)&&String(edge.metadata?.triggerKey||edge.metadata?.triggerType||row.triggerKey)===String(row.triggerKey));if(!exists)edges.push({from:id,to:channelId,type:'vbd_outputs_channel',label:`触发项草稿：${row.label}`,style:'dashed',pathGroupId:'draft',visualStyle:'draft-highlight',referenceEdge:false,metadata:{draft:true,draftPreview:true,logicChainDraftOverlay:true,dataLogicChainVbdTriggerChannelDraftEdge:true,dataLogicChainVbdTriggerGraphRenderBeforeSave:true,dataLogicChainVbdTriggerStableIdentity:true,dataLogicChainVbdTriggerNoDuplicateCard:true,dataLogicChainVbdTriggerTargetChannelOnly:true,triggerType:row.type,triggerKey:row.triggerKey,stableTriggerIdentity:row.stableTriggerIdentity,saveUsesCanonicalChannel:true}});});});return {...graph,nodes,edges,metadata:{...(graph.metadata||{}),dataLogicChainVbdTriggerGraphRenderBeforeSave:true,vbdTriggerDraftGraphRenderBeforeSave:true,dataLogicChainVbdTriggerStableIdentity:true,dataLogicChainVbdTriggerNoDuplicateCard:true,dataLogicChainVbdTriggerTargetChannelOnly:true}};};
                """)
.append("""
                function logicChainCaptureRetryableStatus(draft){return !!(draft?.logicChainDraftContext&&['cancelled','failed','expired'].includes(String(draft.status||''))&&!draft.active);}
                function logicChainFindVbdDraftForCapture(ctx){const e=appState.logicChainEditor;if(!e?.active)return null;const matches=d=>d&&String(d.kind||'').toLowerCase()==='virtual_block_device'&&(!ctx?.deviceId||sameDeviceRef(d.deviceId||d.targetId,ctx.deviceId));let d=matches(e.existingEdit)?e.existingEdit:null;if(!d)d=(e.existingNodeEdits||[]).find(matches)||null;if(d&&e.existingEdit!==d)e.existingEdit=d;return d;}
                function logicChainCaptureRestartDisabledReason(draft){if(!draft?.logicChainDraftContext)return '缺少 Logic Chain 捕获上下文。';const e=appState.logicChainEditor;if(!e?.active)return 'Logic Chain draft session 已关闭。';if(!e.lockId||e.lockLost)return 'Logic Chain edit lock 已失效。';if(draft.logicChainDraftContext.logicChainEditLockId&&draft.logicChainDraftContext.logicChainEditLockId!==e.lockId)return 'Logic Chain edit lock 已变化，请重新打开触发项。';const d=logicChainFindVbdDraftForCapture(draft.logicChainDraftContext);if(!d)return 'VBD trigger context 不存在。';if(!(draft.players||[]).length)return '没有可用在线玩家。';if(!draft.targetPlayerName)return '请选择在线玩家。';return '';}
                function logicChainCaptureRetryFooter(draft,kind){const item=kind==='item',closeAttrs=item?singleItemSubmitActionAttrs('single-item-submit-close',draft.deviceId,!!draft.saving):containerTemplateActionAttrs('container-template-close',draft.deviceId,!!draft.saving),reason=logicChainCaptureRestartDisabledReason(draft),disabled=!!draft.saving,startAttrs=item?singleItemSubmitActionAttrs('single-item-submit-start',draft.deviceId,disabled,reason||'重新打开游戏内 GUI 并复用当前 Logic Chain VBD trigger context。'):containerTemplateActionAttrs('container-template-start',draft.deviceId,disabled,reason||'重新打开游戏内 GUI 并复用当前 Logic Chain VBD trigger context。'),state=String(draft.status||''),failed=state==='failed',label=item?'重新打开 itemSubmit 条件 GUI':'重新打开 container 捕获 GUI',stateAttr=item?'data-logic-chain-vbd-itemsubmit-capture-button-state="retry"':'data-logic-chain-vbd-container-capture-button-state="retry"';return `<button class="wa-btn ghost" ${closeAttrs}>${icon('close')}<span>返回触发项</span></button><button class="wa-btn primary" ${startAttrs} data-logic-chain-vbd-capture-button-state="retry" ${stateAttr} data-logic-chain-vbd-capture-retry-click-capture="true" data-logic-chain-vbd-capture-retry-pointerup="true" data-logic-chain-vbd-capture-retry-not-disabled-by-precheck="true" data-logic-chain-vbd-capture-cancelled-restart-button="${failed?'false':'true'}" data-logic-chain-vbd-capture-failed-restart-button="${failed?'true':'false'}">${icon('selection')}<span>${draft.saving?'启动中...':label}</span></button>`;}
                function logicChainCaptureRetryNote(draft){if(!logicChainCaptureRetryableStatus(draft))return '';const reason=logicChainCaptureRestartDisabledReason(draft);return reason?`<span data-logic-chain-vbd-capture-fail-closed-writeback="true">点击后会重新校验：${esc(reason)}</span>`:'<span data-logic-chain-vbd-capture-cancelled-restart-button="true">可直接重新打开 GUI 并继续当前触发项草稿。</span>';}
                const singleItemSubmitStatusLineBeforeV17=singleItemSubmitStatusLine;singleItemSubmitStatusLine=function(draft){const html=singleItemSubmitStatusLineBeforeV17(draft),note=logicChainCaptureRetryNote(draft);return note?html.replace('</div>',`${note}</div>`):html;};
                const containerTemplateStatusLineBeforeV17=containerTemplateStatusLine;containerTemplateStatusLine=function(draft){const html=containerTemplateStatusLineBeforeV17(draft),note=logicChainCaptureRetryNote(draft);return note?html.replace('</div>',`${note}</div>`):html;};
                const showSingleItemSubmitSessionModalBeforeV17=showSingleItemSubmitSessionModal;showSingleItemSubmitSessionModal=function(deviceId){const draft=appState.singleItemSubmitSession;if(logicChainCaptureRetryableStatus(draft)&&sameDeviceRef(draft.deviceId,deviceId)){openWebAdminModal('Logic Chain itemSubmit 捕获',singleItemSubmitSessionBody(draft),logicChainCaptureRetryFooter(draft,'item'),{className:'wa-config-modal wa-single-item-submit-modal',onClose:async()=>closeSingleItemSubmitSessionModal(draft.deviceId)});return;}return showSingleItemSubmitSessionModalBeforeV17(deviceId);};
                const showContainerTemplateSessionModalBeforeV17=showContainerTemplateSessionModal;showContainerTemplateSessionModal=function(deviceId){const draft=appState.containerTemplateSession;if(logicChainCaptureRetryableStatus(draft)&&sameDeviceRef(draft.deviceId,deviceId)){openWebAdminModal('Logic Chain container 捕获',containerTemplateSessionBody(draft),logicChainCaptureRetryFooter(draft,'container'),{className:'wa-config-modal wa-container-template-modal',onClose:async()=>closeContainerTemplateSessionModal(draft.deviceId)});return;}return showContainerTemplateSessionModalBeforeV17(deviceId);};
                """)
.append("""
                function logicChainMergeCapturedRequirements(current,rows,ctx,kind){const list=Array.isArray(current)?current.slice():[], captured=(rows||[]).map((r,i)=>({...r,captureDraftId:r.captureDraftId||ctx?.captureDraftId||'',requirementId:r.requirementId||`${kind}-${ctx?.captureDraftId||'capture'}-${i+1}`}));const index=Number(ctx?.requirementIndex??-1);if(index>=0&&captured.length===1){list[index]=captured[0];return list.filter(Boolean);}return captured;}
                applyLogicChainExistingVbdItemSubmitCapture=function(status,ctx){const d=logicChainFindVbdDraftForCapture({...ctx,deviceId:ctx?.deviceId||appState.singleItemSubmitSession?.deviceId});if(!d)return false;d.virtualBlockDevice=d.virtualBlockDevice||{};if(!Array.isArray(status.logicChainItemSubmitRequirements)){toast(status.message||'itemSubmit 捕获结果缺少 requirement payload。');return false;}const rows=status.logicChainItemSubmitRequirements;d.virtualBlockDevice.itemSubmitEnabled=status.logicChainItemSubmitEnabled!==false&&rows.length>0;d.virtualBlockDevice.itemSubmitConsumeEnabled=status.logicChainItemSubmitConsumeEnabled===true;d.virtualBlockDevice.itemSubmitConsumeOrder=status.logicChainItemSubmitConsumeOrder||d.virtualBlockDevice.itemSubmitConsumeOrder||'HOTBAR_FIRST';d.virtualBlockDevice.itemSubmitRequirements=logicChainMergeCapturedRequirements(d.virtualBlockDevice.itemSubmitRequirements,rows,ctx,'logic-chain-item');d.virtualBlockDevice.selectedTriggerType='right_click';if(appState.singleItemSubmitSession?.logicChainDraftContext)appState.singleItemSubmitSession.logicChainDraftApplied=true;logicChainExistingVbdUiState(d).page='detail';logicChainUpsertExistingNodeEditDraft(appState.logicChainEditor,d);appState.logicChainEditor.dirty=logicChainEditorHasDraftContent(appState.logicChainEditor);logicChainScheduleVbdNativeTriggerDraftGraphRefresh();toast(status.message||'itemSubmit 捕获已回填 Logic Chain 草稿。');return true;};
                applyLogicChainExistingVbdContainerCapture=function(status,ctx){const d=logicChainFindVbdDraftForCapture({...ctx,deviceId:ctx?.deviceId||appState.containerTemplateSession?.deviceId});if(!d)return false;d.virtualBlockDevice=d.virtualBlockDevice||{};if(!Array.isArray(status.logicChainContainerRequirements)){toast(status.message||'container 捕获结果缺少 requirement payload。');return false;}const rows=status.logicChainContainerRequirements;d.virtualBlockDevice.containerRequirements=logicChainMergeCapturedRequirements(d.virtualBlockDevice.containerRequirements,rows,ctx,'logic-chain-container');d.virtualBlockDevice.selectedTriggerType='container_change';if(appState.containerTemplateSession?.logicChainDraftContext)appState.containerTemplateSession.logicChainDraftApplied=true;logicChainExistingVbdUiState(d).page='detail';logicChainUpsertExistingNodeEditDraft(appState.logicChainEditor,d);appState.logicChainEditor.dirty=logicChainEditorHasDraftContent(appState.logicChainEditor);logicChainScheduleVbdNativeTriggerDraftGraphRefresh();toast(status.message||'container 捕获已回填 Logic Chain 草稿。');return true;};
                function logicChainCapturePayloadHasRequirements(kind,payload){return Array.isArray(kind==='item'?payload?.logicChainItemSubmitRequirements:payload?.logicChainContainerRequirements);}
                function logicChainCaptureWritebackSuccess(kind,draft){draft.logicChainDraftApplied=true;if(kind==='item')appState.singleItemSubmitSession=null;else appState.containerTemplateSession=null;showLogicChainExistingEditModalRestoringVbd(logicChainExistingVbdPageKey(appState.logicChainEditor?.existingEdit,'detail'));}
                function logicChainShowCaptureWritebackFailure(kind,draft,message){draft.errors=[{message:message||'游戏内捕获结果未能回填当前 Logic Chain draft，请保持窗口并重新捕获。'}];draft.status='failed';draft.active=false;draft.message=message||draft.message||'捕获结果回填失败。';if(kind==='item'){appState.singleItemSubmitSession=draft;showSingleItemSubmitSessionModal(draft.deviceId);}else{appState.containerTemplateSession=draft;showContainerTemplateSessionModal(draft.deviceId);}}
                async function logicChainFetchCaptureStatusForWriteback(kind,draft,event){try{const endpoint=kind==='item'?'single-item-submit-session':'container-template-session',url=`/api/webadmin/virtual-block-devices/${encodeURIComponent(draft.deviceId)}/${endpoint}/status?sessionId=${encodeURIComponent(draft.sessionId||'')}`,status=await api(url),sessionId=kind==='item'?singleItemSubmitSessionId(status):containerTemplateSessionId(status);if(sessionId&&draft.sessionId&&sessionId!==draft.sessionId)return;const apply=kind==='item'?applyLogicChainExistingVbdItemSubmitCapture(status,draft.logicChainDraftContext):applyLogicChainExistingVbdContainerCapture(status,draft.logicChainDraftContext);if(apply){logicChainCaptureWritebackSuccess(kind,draft);return;}logicChainShowCaptureWritebackFailure(kind,draft,status.message||event?.summary||'捕获结果回填失败。');}catch(err){logicChainShowCaptureWritebackFailure(kind,draft,err.message||event?.summary||'捕获结果回填失败。');}}
                function logicChainApplyCaptureRealtimeWriteback(kind,draft,payload,event){const saved=['saved','completed'].includes(String(draft.status||''));if(!saved||!draft.logicChainDraftContext)return false;if(!logicChainCapturePayloadHasRequirements(kind,payload)){draft.message='已收到游戏内保存事件，正在同步最终捕获结果...';if(kind==='item'){appState.singleItemSubmitSession=draft;showSingleItemSubmitSessionModal(draft.deviceId);}else{appState.containerTemplateSession=draft;showContainerTemplateSessionModal(draft.deviceId);}logicChainFetchCaptureStatusForWriteback(kind,draft,event);return true;}const apply=kind==='item'?applyLogicChainExistingVbdItemSubmitCapture(payload,draft.logicChainDraftContext):applyLogicChainExistingVbdContainerCapture(payload,draft.logicChainDraftContext);if(apply){logicChainCaptureWritebackSuccess(kind,draft);return true;}logicChainShowCaptureWritebackFailure(kind,draft,payload.message||event?.summary||'捕获结果回填失败。');return true;}
                const handleSingleItemSubmitSessionRealtimeEventBeforeV17=handleSingleItemSubmitSessionRealtimeEvent;handleSingleItemSubmitSessionRealtimeEvent=function(event){const type=String(event?.type||'');if(!type.startsWith('single_item_submit_template_session_'))return;const draft=appState.singleItemSubmitSession,payload=event.payload||{};if(draft?.logicChainDraftContext){const sessionId=singleItemSubmitSessionId(payload)||singleItemSubmitSessionId(event);if(draft.sessionId&&sessionId&&draft.sessionId!==sessionId)return;draft.sessionId=sessionId||draft.sessionId||'';if(type==='single_item_submit_template_session_saved')draft.status='saved';else if(type==='single_item_submit_template_session_failed')draft.status='failed';else if(type==='single_item_submit_template_session_cancelled')draft.status='cancelled';else if(type==='single_item_submit_template_session_expired')draft.status='expired';draft.active=!['saved','completed','cancelled','failed','expired'].includes(String(draft.status||''));draft.message=event.summary||payload.message||draft.message||'';if(!draft.active){draft.lockId='';draft.lock=null;stopSingleItemSubmitSessionHeartbeat();stopSingleItemSubmitSessionStatusPoll();cancelSingleItemSubmitCancelConfirm();if(logicChainApplyCaptureRealtimeWriteback('item',draft,payload,event))return;}showSingleItemSubmitSessionModal(draft.deviceId);return;}return handleSingleItemSubmitSessionRealtimeEventBeforeV17(event);};
                const handleContainerTemplateSessionRealtimeEventBeforeV17=handleContainerTemplateSessionRealtimeEvent;handleContainerTemplateSessionRealtimeEvent=function(event){const type=String(event?.type||'');if(!type.startsWith('container_template_session_'))return;const draft=appState.containerTemplateSession,payload=event.payload||{};if(draft?.logicChainDraftContext){const sessionId=containerTemplateSessionId(payload)||containerTemplateSessionId(event);if(draft.sessionId&&sessionId&&draft.sessionId!==sessionId)return;draft.sessionId=sessionId||draft.sessionId||'';if(type==='container_template_session_saved')draft.status='saved';else if(type==='container_template_session_failed')draft.status='failed';else if(type==='container_template_session_cancelled')draft.status='cancelled';else if(type==='container_template_session_expired')draft.status='expired';draft.active=!['saved','completed','cancelled','failed','expired'].includes(String(draft.status||''));draft.message=event.summary||payload.message||draft.message||'';if(!draft.active){draft.lockId='';draft.lock=null;stopContainerTemplateSessionHeartbeat();stopContainerTemplateSessionStatusPoll();cancelContainerTemplateCancelConfirm();if(logicChainApplyCaptureRealtimeWriteback('container',draft,payload,event))return;}showContainerTemplateSessionModal(draft.deviceId);return;}return handleContainerTemplateSessionRealtimeEventBeforeV17(event);};
                """)
.append("""
                function logicChainVbdNodeMatchesDraft(node,d){const target=String(d?.deviceId||d?.targetId||'');if(!target||!node)return false;const ref=logicChainDeviceTargetId(node,'virtual_block_device')||node.refId||node.metadata?.deviceId||node.metadata?.targetId||node.metadata?.ownerId||'';return logicChainDeviceNodeKind(node)==='virtual_block_device'&&sameDeviceRef(ref,target);}
                const logicChainFindDraftTargetNodeBeforeV17SourceCard=logicChainFindDraftTargetNode;
                logicChainFindDraftTargetNode=function(nodes,d){if(String(d?.kind||d?.nodeType||'').toLowerCase()==='virtual_block_device'){const ids=[d?.sourceNodeId,appState.logicChainCanvas?.selectedNodeId].filter(Boolean).map(String);for(const id of ids){const n=(nodes||[]).find(node=>String(node?.id||'')===id);if(n&&logicChainVbdNodeMatchesDraft(n,d))return n;}const same=(nodes||[]).filter(node=>logicChainVbdNodeMatchesDraft(node,d));if(same.length)return same.find(node=>!logicChainIsReferenceNode(node))||same[0];}return logicChainFindDraftTargetNodeBeforeV17SourceCard(nodes,d);};
                function logicChainVbdTriggerOutputTypeMatches(selected,type){const s=String(selected||'').toLowerCase(),t=String(type||'').toLowerCase();if(s==='redstone_powered')return t==='redstone_powered'||t==='redstone_powered_off';if(s==='blockstate')return t==='blockstate'||t==='blockstate_exit';return t===s;}
                function logicChainVbdOutputRowsForSelectedTrigger(d,draft){const selected=String(d?.virtualBlockDevice?.selectedTriggerType||logicChainExistingVbdSelectedTrigger(d)||'right_click').toLowerCase();return logicChainVbdNativeTriggerOutputRows(draft?.values||{}).filter(row=>logicChainVbdTriggerOutputTypeMatches(selected,row.type));}
                function logicChainVbdTriggerOutputSummaryRows(rows){return rows.length?rows.slice(0,3).map(row=>`${row.label} -> ${row.channel}`).join('；')+(rows.length>3?'；...':''):'当前触发项草稿尚未设置输出频道';}
                logicChainApplyVbdNativeTriggerDraftGraphOverlay=function(graph){const editor=appState.logicChainEditor||{};if(!editor.active||!graph?.nodes)return graph;const nodes=(graph.nodes||[]).map(n=>({...n,metadata:{...(n.metadata||{})}})),nodeMap={};nodes.forEach(n=>{if(n.id)nodeMap[n.id]=n;});let edges=(graph.edges||[]).map(e=>({...e,metadata:{...(e.metadata||{})}}));logicChainExistingNodeDraftsForPreview(editor).forEach(d=>{if(String(d?.kind||'').toLowerCase()!=='virtual_block_device')return;const draft=logicChainVbdStoredNativeTriggerDraft(d);if(!draft||!vbdNativeTriggerDirty(draft))return;const target=logicChainFindDraftTargetNode(nodes,d),id=target?.id;if(!target||!id)return;const afterRows=logicChainVbdOutputRowsForSelectedTrigger(d,draft),afterChannels=new Set(afterRows.map(row=>row.channel)),summary=logicChainVbdTriggerOutputSummaryRows(afterRows);target.subtitle=`触发项草稿 · ${summary}`;target.metadata={...(target.metadata||{}),dataLogicChainVbdTriggerGraphRenderBeforeSave:true,vbdTriggerDraftGraphRenderBeforeSave:true,vbdTriggerDraftSummary:summary,dataLogicChainVbdTriggerStableIdentity:true,dataLogicChainVbdTriggerNoDuplicateCard:true,dataLogicChainVbdTriggerTargetChannelOnly:true,dataLogicChainVbdTriggerSourceCardDraft:true};edges=edges.filter(edge=>{if(edge.from!==id||edge.type!=='vbd_outputs_channel')return true;const channel=logicChainVbdDraftEdgeTargetChannel(edge,nodeMap);return channel&&afterChannels.has(channel);});afterRows.forEach(row=>{logicChainEnsureDraftChannelNode(nodes,nodeMap,row.channel,logicChainDraftChannelInfo(editor,row.channel));const channelId=logicChainDraftChannelNodeId(row.channel),exists=edges.some(edge=>edge.from===id&&edge.type==='vbd_outputs_channel'&&logicChainOverlayEdgeMatchesChannel(edge,nodeMap,'to',row.channel)&&String(edge.metadata?.triggerKey||edge.metadata?.triggerType||row.triggerKey)===String(row.triggerKey));if(!exists)edges.push({from:id,to:channelId,type:'vbd_outputs_channel',label:`触发项草稿：${row.label}`,style:'dashed',pathGroupId:'draft',visualStyle:'draft-highlight',referenceEdge:false,metadata:{draft:true,draftPreview:true,logicChainDraftOverlay:true,dataLogicChainVbdTriggerChannelDraftEdge:true,dataLogicChainVbdTriggerGraphRenderBeforeSave:true,dataLogicChainVbdTriggerStableIdentity:true,dataLogicChainVbdTriggerNoDuplicateCard:true,dataLogicChainVbdTriggerTargetChannelOnly:true,dataLogicChainVbdTriggerSourceCardDraft:true,triggerType:row.type,triggerKey:row.triggerKey,stableTriggerIdentity:row.stableTriggerIdentity,saveUsesCanonicalChannel:true}});});});return {...graph,nodes,edges,metadata:{...(graph.metadata||{}),dataLogicChainVbdTriggerGraphRenderBeforeSave:true,vbdTriggerDraftGraphRenderBeforeSave:true,dataLogicChainVbdTriggerStableIdentity:true,dataLogicChainVbdTriggerNoDuplicateCard:true,dataLogicChainVbdTriggerTargetChannelOnly:true,dataLogicChainVbdTriggerSourceCardDraft:true}};};
                async function logicChainResetSingleItemSubmitRetryDraft(deviceId){const draft=syncSingleItemSubmitSessionDraftFromForm(deviceId)||appState.singleItemSubmitSession;if(!logicChainCaptureRetryableStatus(draft)||!sameDeviceRef(draft.deviceId,deviceId))return false;await releaseSingleItemSubmitSessionLock(draft,true);draft.lockId='';draft.lock=null;draft.sessionId='';draft.active=false;draft.status='ready';draft.saving=false;draft.errors=[];draft.message='正在重新打开 itemSubmit 条件 GUI...';appState.singleItemSubmitSession=draft;stopSingleItemSubmitSessionHeartbeat();stopSingleItemSubmitSessionStatusPoll();cancelSingleItemSubmitCancelConfirm();return true;}
                const startSingleItemSubmitSessionBeforeV17Retry=startSingleItemSubmitSession;startSingleItemSubmitSession=async function(deviceId){await logicChainResetSingleItemSubmitRetryDraft(deviceId);return await startSingleItemSubmitSessionBeforeV17Retry(deviceId);};
                async function logicChainResetContainerTemplateRetryDraft(deviceId){const draft=syncContainerTemplateSessionDraftFromForm(deviceId)||appState.containerTemplateSession;if(!logicChainCaptureRetryableStatus(draft)||!sameDeviceRef(draft.deviceId,deviceId))return false;await releaseContainerTemplateSessionLock(draft,true);draft.lockId='';draft.lock=null;draft.sessionId='';draft.active=false;draft.status='ready';draft.saving=false;draft.errors=[];draft.message='正在重新打开 container 捕获 GUI...';appState.containerTemplateSession=draft;stopContainerTemplateSessionHeartbeat();stopContainerTemplateSessionStatusPoll();cancelContainerTemplateCancelConfirm();return true;}
                const startContainerTemplateSessionBeforeV17Retry=startContainerTemplateSession;startContainerTemplateSession=async function(deviceId){await logicChainResetContainerTemplateRetryDraft(deviceId);return await startContainerTemplateSessionBeforeV17Retry(deviceId);};
                async function logicChainRestartVbdCaptureFromRetryButton(button,kind,deviceId){if(button?.dataset?.logicChainCaptureRestartPending==='true')return;button.dataset.logicChainCaptureRestartPending='true';try{if(kind==='item')await startSingleItemSubmitSession(deviceId||appState.singleItemSubmitSession?.deviceId||'');else await startContainerTemplateSession(deviceId||appState.containerTemplateSession?.deviceId||'');}finally{setTimeout(()=>{if(button?.dataset)delete button.dataset.logicChainCaptureRestartPending;},250);}}
                function handleLogicChainVbdCaptureRetryDelegatedClick(event){const target=event?.target;if(!target?.closest)return false;const button=target.closest('#wa-modal-root [data-logic-chain-vbd-capture-retry-click-capture="true"]');if(!button)return false;if(button.dataset.logicChainCaptureRestartPending==='true'){event.preventDefault();event.stopPropagation();return true;}if(button.disabled)return false;const action=String(button.dataset.action||''),deviceId=button.dataset.deviceId||'';if(action==='single-item-submit-start'){event.preventDefault();event.stopPropagation();logicChainRestartVbdCaptureFromRetryButton(button,'item',deviceId);return true;}if(action==='container-template-start'){event.preventDefault();event.stopPropagation();logicChainRestartVbdCaptureFromRetryButton(button,'container',deviceId);return true;}return false;}
                const logicChainNodeMarkersBeforeV17SourceCard=logicChainNodeMarkers;logicChainNodeMarkers=function(node){const base=logicChainNodeMarkersBeforeV17SourceCard(node),m=node?.metadata||{},extras=[];if(m.dataLogicChainVbdTriggerSourceCardDraft)extras.push('data-logic-chain-vbd-trigger-source-card-draft="true"');return `${base}${extras.length?' '+extras.join(' '):''}`;};
                """).toString();
    }
}
